version: '3'
networks:
  wordpress_network:

#volumes:
#  fs-xxxxx:    
#    driver: rexray or efs
#    driver_opts:
#      share: "fs-xxxxx"


services:
  webserver:
    image: richarvey/nginx-php-fpm:latest
    ports:
      - 80:80
    networks:
      - wordpress_network
    volumes:
      - ../wordpress:/var/www/html
#      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
#      - ./nginx/ssl-key:/etc/nginx/ssl-key
    deploy:
      mode: replicated
      replicas: 3
      labels: [APP=WEBSERVER]
      restart_policy:
        condition: on-failure

  mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=wvlyfvpjkcV8otg;hpgshp
      - MYSQL_DATABASE=wpdb
    volumes:
      - ../../mysql-data:/var/lib/mysql
    networks:
      - wordpress_network
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=DB]
      restart_policy:
        condition: on-failure
